apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: blog-ghost-dep
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: blog-ghost
    spec:
      containers:
      - name: ghost
        image: ghost:1-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - name: ghostport
          containerPort: 2368
        env:
        - name: database__client
          value: mysql
        - name: database__connection__host
          value: blog-db-svc
        - name: database__connection__port
          value: "8888"
        - name: database__connection__user
          valueFrom: 
            configMapKeyRef:
              name: myconfig
              key: dbusername
        - name: database__connection__password
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: dbpwd
        - name: database__connection__database
          valueFrom: 
            configMapKeyRef:
              name: myconfig
              key: dbname
          
---
apiVersion: v1
kind: Service
metadata:
  name: blog-ghost-svc
spec:
  ports:
  - port: 8888
    nodePort: 32005
    targetPort: ghostport
    protocol: TCP
  selector:
    app: blog-ghost
  type: NodePort