apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  dbpwd: d2VsY29tZQ==

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: myconfig
data:
  dbname: ghost
  dbusername: root  