apiVersion: v1
kind: Pod
metadata:
  name: my-nginx
  labels:
    app: helloworld2
spec:
  containers:
  - name: web
    image: nginx:alpine
    ports:
    - name: nginxport
      containerPort: 80